// This file is auto-generated by scripts/generate-sidebar.js
// Do not edit this file directly.

export default [
  {
    "name": "首页",
    "path": "README"
  },
  {
    "name": "Guide",
    "children": [
      {
        "name": "Advanced",
        "path": "guide/advanced"
      },
      {
        "name": "Introduction",
        "path": "guide/introduction"
      }
    ]
  },
  {
    "name": "Api",
    "children": [
      {
        "name": "Api Overview",
        "path": "api/api-overview"
      },
      {
        "name": "Endpoints",
        "path": "api/endpoints"
      }
    ]
  },
  {
    "name": "人生篇",
    "children": [
      {
        "name": "关于厦马",
        "path": "人生篇/关于厦马"
      }
    ]
  },
  {
    "name": "入学篇",
    "children": [
      {
        "name": "吉隆坡机场指南",
        "path": "入学篇/吉隆坡机场指南"
      },
      {
        "name": "宿舍与室友",
        "path": "入学篇/宿舍与室友"
      },
      {
        "name": "行前指南",
        "path": "入学篇/行前指南"
      }
    ]
  },
  {
    "name": "生活篇",
    "children": [
      {
        "name": "好物分享",
        "path": "生活篇/好物分享"
      },
      {
        "name": "马来西亚日常生活",
        "path": "生活篇/马来西亚日常生活"
      },
      {
        "name": "如何与行政部门打交道",
        "path": "生活篇/如何与行政部门打交道"
      },
      {
        "name": "学校设施",
        "path": "生活篇/学校设施"
      },
      {
        "name": "学校周边",
        "path": "生活篇/学校周边"
      }
    ]
  },
  {
    "name": "学习篇",
    "children": [
      {
        "name": "毕业论文与毕业设计",
        "path": "学习篇/毕业论文与毕业设计"
      },
      {
        "name": "全专业通用网站",
        "path": "学习篇/全专业通用网站"
      },
      {
        "name": "善用工具",
        "path": "学习篇/善用工具"
      },
      {
        "name": "小组作业生存指南",
        "path": "学习篇/小组作业生存指南"
      },
      {
        "name": "自学",
        "path": "学习篇/自学"
      }
    ]
  }
];
